apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
namespace: int
images:
- name: nginx
  newName: nginx  # {"$imagepolicy": "default:nginx-image-policy:name"}
  newTag: 1.10-alpine # {"$imagepolicy": "default:nginx-image-policy:tag"}

